package org.challenge.exception;

public class UserNotFoundException extends RuntimeException {
}
